Added new module: Motivation
the-vision/jarvis-telegram pull request #79
Opened 2020-05-25 08:02 UTC by adityabisoi

Closes #78 

@swapagarwal @TeAmP0is0N Please review.

2020-05-25 12:22 UTC, RohitRathore1 requested changes
@adityabisoi Resolve conflicts.

2020-05-30 03:02 UTC, RohitRathore1 approved these changes

2020-06-01 07:21 UTC, swapagarwal commented on modules.py
> +        url = "https://type.fit/api/quotes"
This API returns a lot of data. Need to find another one.

2020-06-01 07:22 UTC, swapagarwal commented on modules.py
> +        i=random.randint(1,1643)
Magic number.

2020-06-01 07:22 UTC, swapagarwal commented
Not the right fit for the bot.

2020-06-01 07:22 UTC, closed without merging